### ISSUE TITLE
use fingerprint for remote sudo

### ISSUE THREAD

**Issue by nhooyr** [hamzasood/pam_touchid#5]
I want to use my fingerprint to use sudo on my VPS through ssh. Is this possible?

**Comment by cqexbesd** [comment]
> On 13. May 2017, at 02:03, Anmol Sethi <notifications@github.com> wrote:
> 
> I want to use my fingerprint to use sudo on my VPS through ssh. Is this possible?
> 
It would not be easy. It certainly won't work out of the box. The VPS has no access to your fingerprint sensor.

In theory you could do some tunnelling across the ssh session but how you could make that secure I don't know. 

Andrew

**Comment by nhooyr** [comment]
Yup, I figured. Thanks!
