### ISSUE TITLE
pam_touchid fails (times out) when used within tmux

### ISSUE THREAD

**Issue by ameg** [hamzasood/pam_touchid#6]
When using this within tmux, the popup doesn't appear, but instead after ~5 seconds it falls back to password authentication:

```
mbp:~ user$ sudo -l
UI activation timed out.
Password:
```

Installing tmux-pasteboard and using this in conjunction with the `reattach-to-user-namespace` command appears to work. For example, by setting up the following alias:

`alias sudo='reattach-to-user-namespace sudo'`

Do you know if there is a way to fix this properly without such a workaround?

**Comment by grgar** [comment]
Adding pam_reattach (as optional) from [fabianishere/pam_reattach](https://github.com/fabianishere/pam_reattach) above the Touch ID PAM fixed the issue for me. I am using Apple's Touch ID PAM but I suspect it should work for this too.
